# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
  repositories:
  - repository: pipeline-tasks-template-for-node-sample-project
    type: github
    endpoint: 'github_sciortinomrc'
    name: sciortinomrc/pipeline-tasks-template-for-node-sample-project
    ref: refs/heads/master

pool:
  vmImage: ubuntu-latest

jobs:
- job: meterian_analysis
  displayName: "Meterian Security Analysis"
  
  pool:
    vmImage: ubuntu-16.04

  steps:
  - checkout: self
  - checkout: pipeline-tasks-template-for-node-sample-project
  - template: template.yaml@pipeline-tasks-template-for-node-sample-project
    parameters:
      ProjectWorkingDirectory: $(Build.SourcesDirectory)/node-sample-project-with-azure-pipeline/project/subfolder